#!/bin/bash

if [[ "$1" == "" ]]
then
	echo "how many sticks would you like to play with?"
	read num	#tracks stick count
else
	num=$1 #assigns player-entered stick count from command-line
fi

while [[ $num -gt 0 ]]
do
	#num=$(($num-$(($num%4))))
	
	var=$(($num%4))	
	echo $var
	echo "We are in the loop"
done






